import { Header, Main1, Main2, Main3, Main4, Main5 } from "components";
import type { NextPage } from "next";
import Head from "next/head";
import Wave from "public/vector/wave.svg";
import Wave2 from "public/vector/wave2.svg";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Wave className="wave" />
			<Wave2 className="wave2" />

			<Header />
			<Main1 />
			<Main2 />
			<Main3 />
			<Main4 />
			<Main5 />
		</div>
	);
};

export default Home;
